# Generated by Django 4.1.5 on 2023-01-07 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UX_UI_design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_profession',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
