# Generated by Django 4.1.5 on 2023-01-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UX_UI_design', '0002_alter_about_profession_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_salary', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Geography_vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_vacancy', models.CharField(max_length=100)),
                ('vacancy', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('average_salary', models.IntegerField()),
                ('average_salary_prof', models.IntegerField()),
                ('vacancy_count', models.IntegerField()),
                ('vacancy_count_prof', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('skill', models.CharField(max_length=100)),
            ],
        ),
    ]
