# Generated by Django 4.1.5 on 2023-01-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UX_UI_design', '0003_geography_salary_geography_vacancy_relevance_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill',
            new_name='skill_1',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_10',
            field=models.CharField(default='sa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_2',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_3',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_4',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_5',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_6',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_7',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_8',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_9',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
    ]
