# Generated by Django 4.1.5 on 2023-01-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UX_UI_design', '0005_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='d', upload_to=''),
            preserve_default=False,
        ),
    ]
