# Generated by Django 4.1.5 on 2023-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UX_UI_design', '0006_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_10',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_7',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_8',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_9',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about_profession',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/djangoProject/img'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/djangoProject/img'),
        ),
    ]
